const serviceIcons = {
    'ec2': '/assets/service-icon/ec2.png',
    'ebs': '/assets/service-icon/ec2.png',
    'es': '/assets/service-icon/ec2.png',
    'aurora': '/assets/service-icon/aurora.png',
    'cloud-trail': '/assets/service-icon/cloud-trail.png',
    'cloudtrail': '/assets/service-icon/cloud-trail.png',
    'cloud-watch': '/assets/service-icon/cloud-watch.png',
    'cw': '/assets/service-icon/cloud-watch.png',
    'iam': '/assets/service-icon/iam.png',
    'kms': '/assets/service-icon/iam.png',
    'lambda': '/assets/service-icon/lambda.png',
    'rds': '/assets/service-icon/rds.png',
    'redshift': '/assets/service-icon/redshift.png',
    's3': '/assets/service-icon/s3.png',
    'vpc': '/assets/service-icon/vpc.png',
    'cloud-front': '/assets/service-icon/cloud-front.png',
    'elasticsearch': '/assets/service-icon/elastic-search.png',
    'sns': '/assets/service-icon/sns.png',
    'route53': '/assets/service-icon/route53.png',
    'sqs': '/assets/service-icon/sqs.png',
    'acm': '/assets/service-icon/acm.png',
    'cloud-formation': '/assets/service-icon/cloudformation.png',
    'cf': '/assets/service-icon/cloudformation.png',
    'default': '/assets/service-icon/default.png',
    'icon-awsCloud': '/assets/aws-diagram-icons/AWScloud.png',
    'icon-acm': '/assets/aws-diagram-icons/acm.png',
    'icon-cloud-formation': '/assets/aws-diagram-icons/cloud-formation.png',
    'icon-cloud-front': '/assets/aws-diagram-icons/cloud-front.png',
    'icon-cloud-trail': '/assets/aws-diagram-icons/cloud-trail.png',
    'icon-cloud-watch': '/assets/aws-diagram-icons/cloud-watch.png',
    'icon-ec2': '/assets/aws-diagram-icons/ec2.png',
    'icon-elasticsearch': '/assets/aws-diagram-icons/elasticsearch.png',
    'icon-iam': '/assets/aws-diagram-icons/iam.png',
    'icon-lambda': '/assets/aws-diagram-icons/lambda.png',
    'icon-rds': '/assets/aws-diagram-icons/rds.png',
    'icon-redshift': '/assets/aws-diagram-icons/redshift.png',
    'icon-route53': '/assets/aws-diagram-icons/route53.png',
    'icon-s3': '/assets/aws-diagram-icons/s3.png',
    'icon-sns': '/assets/aws-diagram-icons/sns.png',
    'icon-sqs': '/assets/aws-diagram-icons/sqs.png',
    'cloud_aws': '/assets/images/cloud_aws.png',
    'cloud_azure': '/assets/images/cloud_azure.png',
    'cloud_gcp': '/assets/images/cloud_gcp.png',
    'icon-vpc': '/assets/aws-diagram-icons/vpc.png',
    
}

export const fetchServiceIconPath = (iconName) => {
    return serviceIcons[iconName] ? serviceIcons[iconName] : serviceIcons['default']
}
